name: hn
description: a simple hacker news app.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  flutter_html: ^2.2.1
  timeago: ^3.4.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/PretendardVariable.ttf
